[package]
name = "size_medium"
description = "Medium size example (~50 lines of Slint)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slint.workspace = true
