[package]
name = "size_large"
description = "Large size example (~100 lines of Slint)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slint.workspace = true
