[package]
name = "size_small"
description = "Small size example (~20 lines of Slint)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slint.workspace = true
